version: '3.8'

services:
  lunch_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lunch_service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - lunch_service_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${LS_POSTGRES_NAME}
      POSTGRES_USER: ${LS_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${LS_POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"

volumes:
  lunch_service_db_data:

networks:
  default:
    driver: bridge